Apply most of https://github.com/ome/openmicroscopy/pull/5994
$ curl -sSL https://patch-diff.githubusercontent.com/raw/ome/openmicroscopy/pull/5994.diff | sed -e 's%/components/tools/OmeroPy/%/%g' -e 's%/components/tools/OmeroWeb/%/%g' -e 's%etc/templates/web/%omeroweb/templates/%g' -e 's%/test/unit/clitest/%/test/unit/%g' -e 's%/src/%/%g' | git apply --reject

Checking patch omero/plugins/web.py...
error: while searching for:

import traceback
from datetime import datetime
from omero.cli import DiagnosticsControl
from omero.cli import CLI
import platform

error: patch failed: omero/plugins/web.py:10
Hunk #2 succeeded at 276 (offset 1 line).
error: while searching for:
                         "Web template configuration requires"
                         "wsgi or wsgi-tcp.")

        template_file = "%s.conf.template" % server
        c = file(self._get_web_templates_dir() / template_file).read()
        self.ctx.out(c % d)

    def syncmedia(self, args):
        self.collectstatic()

error: patch failed: omero/plugins/web.py:301
Checking patch test/unit/reference_templates/nginx-development-withoptions.conf...
Checking patch test/unit/reference_templates/nginx-development.conf...
Checking patch test/unit/reference_templates/nginx-location-withoptions.conf...
Checking patch test/unit/reference_templates/nginx-location.conf...
Checking patch test/unit/reference_templates/nginx-withoptions.conf...
Checking patch test/unit/reference_templates/nginx.conf...
Checking patch omeroweb/templates/nginx-development.conf.template...
Checking patch omeroweb/templates/nginx-location.conf.template...
Checking patch omeroweb/templates/nginx.conf.j2...
Checking patch omeroweb/templates/nginx.conf.template...
Applying patch omero/plugins/web.py with 2 rejects...
Rejected hunk #1.
Hunk #2 applied cleanly.
Rejected hunk #3.
Applied patch test/unit/reference_templates/nginx-development-withoptions.conf cleanly.
Applied patch test/unit/reference_templates/nginx-development.conf cleanly.
Applied patch test/unit/reference_templates/nginx-location-withoptions.conf cleanly.
Applied patch test/unit/reference_templates/nginx-location.conf cleanly.
Applied patch test/unit/reference_templates/nginx-withoptions.conf cleanly.
Applied patch test/unit/reference_templates/nginx.conf cleanly.
Applied patch omeroweb/templates/nginx-development.conf.template cleanly.
Applied patch omeroweb/templates/nginx-location.conf.template cleanly.
Applied patch omeroweb/templates/nginx.conf.j2 cleanly.
Applied patch omeroweb/templates/nginx.conf.template cleanly.