Reverting Carlos' commit 899cfc7
This was giving me errors connecting:
AttributeError: 'Connector' object has no attribute 'omero_session_key'
Need to review this logic

Former-commit-id: 2dddb5e3970ef51cb3c0f36a49b7e705535cd3ca